name: "Email updates"

on:
  pull_request_target:

jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - uses: actions/checkout@v4
      with:
        # pull_request_target checks out the base branch by default
        ref: refs/pull/${{ github.event.pull_request.number }}/merge
        fetch-depth: 0
    - name: Automerge if verified email update
      run: |
        # Because we fetch a merge commit, HEAD has two parents:
        # HEAD^1 is the last commit of the base branch
        base=$(git rev-parse HEAD^1)
        # HEAD^2 is the PRs head commit
        head=$(git rev-parse HEAD^2)

        git checkout "$base"
        # To be able to check the diff of the PR, we can't just compare base to head,
        # because that would give differences when the base branch gets new commits.
        # Instead, the merge base is what we need here,
        # this is also what the `git diff base...head` syntax does
        from=$(git merge-base "$base" "$head")
        to=$head

        # The PR can be automerged if it contains 1 deleted and 1 added line in eligible.csv
        # The deleted and added line should both concern the PR author
        changes=$(git diff "$from" "$to" --numstat)
        diff=$(git diff "$from" "$to")
        if [[ $(tr " \t" , <<< "$changes") != "1,1,eligible.csv" ]] || ! grep "^-$AUTHOR_ID," <<< "$diff" || ! grep "^+$AUTHOR_ID," <<< "$diff"; then
          echo "unexpected changes: $changes"
          exit 1
        fi

        # Merge the pull request, notably passing the sha we checked here,
        # to make sure it can't be updated while we're not looking
        gh api \
          --method PUT \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$REPOSITORY/pulls/$PR_NUMBER/merge" \
          -f "sha=$to"

        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/$REPOSITORY/issues/$PR_NUMBER/comments" \
          -f "body=Email update automerged."
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
        REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        AUTHOR_ID: ${{ github.event.pull_request.user.id }}
